universe = docker
docker_image = gjoschka/kinodata3d-b0:2.3.0-cuda12.1
executable = entry.sh

output = runlogs_r/train.out
error = runlogs_r/train.err
log = runlogs_r/train.log
should_transfer_files = YES

request_GPUs = 1
request_CPUs = 8
request_memory = 4G
requirements = (UidDomain == "cs.uni-saarland.de") && (GPUs_GlobalMemoryMb >= 24000)

+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1

